"""
Wires up Marcy's test scoring. Do not edit this file.

It makes `score_tests.py` importable from the repo root and registers the
plugin that writes `scores/scores.json` after every test run.
"""

import sys
from pathlib import Path

REPO_ROOT = Path(__file__).parent
sys.path.insert(0, str(REPO_ROOT))
sys.path.insert(0, str(REPO_ROOT / "src"))

import score_tests  # noqa: E402  (must follow the sys.path setup above)


def pytest_configure(config):
    score_tests.register(config, REPO_ROOT)
